version: '3.9'
services:

  service:
    container_name: cambia
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    image: cambia:latest
  
  postgres-db:
    container_name: postgres-cambia
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cambia
      POSTGRES_PASSWORD: cambia
    build:
      context: .
      dockerfile: database/Dockerfile
    volumes:
      - cambia-postgres:/var/lib/postgresql/data

volumes:
  cambia-postgres:
